const styles = {
  container: {
    height: "100vh",
    overflow: "hidden",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundImage: "url('https://cdn.wallpapersafari.com/3/12/w09t6B.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    fontFamily: "sans-serif",
    padding: 0,
  },
  innerWrapper: {
    display: "flex",
    flexDirection: "row",
    borderRadius: "0.5rem",
    boxShadow: "0 8px 16px rgba(0,0,0,0.1)",
    maxHeight: "90vh",
    width: "95%",
    height: "95%",
    backgroundColor: "rgba(255,255,255,0.95)",
    padding: "1.5rem",
    gap: "1rem",
  },
  sidebar: {
    width: "40%",
    overflowY: "auto",
    paddingRight: "1rem",
  },
  detailsPanel: {
    width: "60%",
    backgroundColor: "#fff",
    padding: "1.5rem",
    borderRadius: "0.5rem",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    overflowY: "auto",
    maxHeight: "100%",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.5rem",
  },
  heading: {
    fontSize: "2rem",
    fontWeight: "bold",
    color: "#1f2937",
  },
  logoutButton: {
    backgroundColor: "#ef4444",
    color: "white",
    padding: "0.5rem 1rem",
    borderRadius: "0.375rem",
    fontWeight: "600",
    cursor: "pointer",
    border: "none",
  },
  searchInput: {
    width: "100%",
    padding: "0.5rem 1rem",
    borderRadius: "0.5rem",
    border: "1px solid #d1d5db",
    marginBottom: "1rem",
    fontSize: "1rem",
  },
  sectionTitle: {
    fontSize: "1.125rem",
    fontWeight: "bold",
    marginTop: "1rem",
    marginBottom: "0.5rem",
    color: "#1f2937",
  },
  listItem: {
    backgroundColor: "#f3f4f6",
    padding: "0.75rem 1rem",
    borderRadius: "0.375rem",
    marginBottom: "0.5rem",
    cursor: "pointer",
  },
  activeItem: {
    backgroundColor: "#dbeafe",
  },
  detailName: {
    fontSize: "1.75rem",
    fontWeight: "bold",
    marginBottom: "1rem",
    color: "#1f2937",
  },
  detailText: {
    margin: "0.5rem 0",
    color: "#374151",
    fontSize: "0.95rem",
  },
  buttonGroup: {
    display: "flex",
    gap: "1rem",
    marginTop: "1rem",
  },
  button: {
    padding: "0.5rem 1rem",
    borderRadius: "0.375rem",
    fontWeight: "600",
    cursor: "pointer",
    border: "none",
  },
  approveBtn: {
    backgroundColor: "#10b981",
    color: "white",
  },
  rejectBtn: {
    backgroundColor: "#ef4444",
    color: "white",
  },
};

export default styles;