const styles = {
    container: {
        height: "100vh",
        overflow: "hidden",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        backgroundImage: "url('https://cdn.wallpapersafari.com/3/12/w09t6B.jpg')",
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        fontFamily: "sans-serif",
        padding: 0,
    },
    innerWrapper: {
        display: "flex",
        flexDirection: "row",
        borderRadius: "0.5rem",
        boxShadow: "0 8px 16px rgba(0,0,0,0.1)",
        overflow: "hidden",
        maxWidth: "1700px",
        width: "100%",
        backgroundColor: "rgba(255,255,255,0.95)",
        maxWidth: "90%",
    },
    box: {
        backgroundColor: "#fff",
        width: "500px",
        padding: "2rem",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
    },
    title: {
        fontSize: "2.5rem",
        fontWeight: "bold",
        color: "#1f2937",
        textAlign: "center",
    },
    highlight: {
        color: "#749cc9",
    },
    subtitle: {
        color: "#4b5563",
        textAlign: "center",
        marginBottom: "1.5rem",
        fontSize: "1rem",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        gap: "0.75rem",
    },
    label: {
        fontSize: "0.875rem",
        fontWeight: 500,
        color: "#374151",
        marginBottom: "0.25rem",
        display: "block",
    },
    input: {
        width: "100%",
        padding: "0.5rem 1rem",
        border: "1px solid #d1d5db",
        borderRadius: "0.5rem",
        fontSize: "1rem",
        boxSizing: "border-box",
    },
    button: {
        backgroundColor: "#416b9f",
        color: "white",
        fontWeight: 600,
        padding: "0.5rem 1rem",
        border: "none",
        borderRadius: "0.5rem",
        cursor: "pointer",
        transition: "background-color 0.2s",
    },
    signupText: {
        textAlign: "center",
        fontSize: "0.875rem",
        color: "#4b5563",
        marginTop: "1rem",
    },
    footer: {
        marginTop: "2rem",
        fontSize: "0.875rem",
        color: "#6b7280",
        textAlign: "center",
    },
    imageContainer: {
        width: "1200px",
        display: "block",
        height: "600px",
    },
    image: {
        width: "100%",
        height: "100%",
        objectFit: "cover",
        display: "block",
    },
    error: {
        color: "red",
        fontSize: "0.75rem",
        marginTop: "0.25rem",
    },
    togglePassword: {
        cursor: "pointer",
        fontSize: "0.75rem",
        color: "#4b5563",
        marginTop: "0.25rem",
        textAlign: "right",
    },
};

export default styles;