// src/styles/signupStyles.js

const styles = {
    container: {
        height: "100vh",
        overflow: "hidden",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "linear-gradient(to bottom right, #5895da, #426fa3)",
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        fontFamily: "sans-serif",
        padding: "1rem",
    },
    innerWrapper: {
        display: "flex",
        flexDirection: "row",
        borderRadius: "0.5rem",
        boxShadow: "0 8px 16px rgba(0,0,0,0.1)",
        overflow: "hidden",
        maxWidth: "1200px",
        width: "100%",
        backgroundColor: "rgba(255,255,255,0.95)",
        maxHeight: "90%",
    },
    box: {
        backgroundColor: "#fff",
        width: "700px",
        padding: "2rem",
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        height: "90vh",
        overflowY: "auto",
        scrollbarWidth: "thin",
        scrollbarColor: "#ccc #fff",
    },
    title: {
        fontSize: "2.3rem",
        fontWeight: "bold",
        color: "#1f2937",
        textAlign: "center",
        marginBottom: "0.1rem",
        paddingTop: "2.2rem",
    },
    highlight: {
        color: "#749cc9",
        textDecoration: "none",
    },
    subtitle: {
        color: "#4b5563",
        textAlign: "center",
        marginBottom: "1.5rem",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        gap: "0.75rem",
    },
    label: {
        fontSize: "0.875rem",
        fontWeight: 500,
        color: "#374151",
        marginBottom: "0.25rem",
        display: "block",
    },
    input: {
        width: "100%",
        padding: "0.5rem 1rem",
        border: "1px solid #d1d5db",
        borderRadius: "0.5rem",
        fontSize: "1rem",
        boxSizing: "border-box",
    },
    errorText: {
        color: "red",
        fontSize: "0.75rem",
        marginTop: "0.25rem",
    },
    instruction: {
        fontSize: "0.85rem",
        color: "#4b5563",
        marginTop: "1rem",
    },
    button: {
        backgroundColor: "#416b9f",
        color: "white",
        fontWeight: 600,
        padding: "0.5rem 1rem",
        border: "none",
        borderRadius: "0.5rem",
        cursor: "pointer",
        transition: "background-color 0.2s",
    },
    image: {
        width: "100%",
        height: "auto",
        objectFit: "cover",
        display: "block",
    },
};

export default styles;
